spring:
  application:
    name: product
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream