spring:
  application:
    #spring项目名称
    name: product
server:
  #服务器端口
  port: 9001
eureka:
  client:
    availability-zones:
      #可用区列表，key为region，value为zone
      region1: defaultZone
    #所在区域，通过这个读取availability-zones获取zone，然后通过zone读取service-url获取对应的eureka url
    #这里的逻辑对应的类是ConfigClusterResolver和ZoneAffinityClusterResolver
    region: region1
    service-url:
      #治理客户端服务域
      #属性eureka.client.service-url.defaultZone代表服务中心的域，将来可以提供给别的微服务注册
      #默认eureka集群,这里必须是defaultZone，不能用-替换大写，与其他的配置不一样，因为实在EurekaClientConfigBean里面写死的
      defaultZone: http://localhost:7001/eureka/
      zone1: http://localhost:7002/eureka/
#这里使用了9001端口，而应用名称为product，这个微服务名称将会注册给服务治理中心。
#而这个应用就会作为这个名称为PRODUCT(注意大写)服务的一个节点。
#治理客户端服务域则是通过属性eureka.client.service-url.defaultZone进行配置的，它也配置了服务治理中心同样的地址，
#这样它就能够注册到之前所配置的服务治理中心。
management:
  endpoints:
    web:
      exposure:
        #management.endpoints.web.exposure.include代表Actuator监控对外暴露的端点，
        #在默认情况下，它只会暴露health和info端点，这里增加了hystrix.stream端点，这样仪表盘才能读到HTTP协议下的hystrix信息流
        include: health,info,hystrix.stream
